javalint:
  stage: test
  image: python:latest
  before_script:
    - mkdir -p public/badges public/lint
    - echo undefined > public/badges/$CI_JOB_NAME.score
    - pip3 install anybadge
    - git clone https://gitlab.esiea.fr/gauthier.heiss/java-file-scorer.git /tmp/java-file-scorer
    - apt update
    - apt install bc -y
    - wget https://download.oracle.com/java/21/latest/jdk-21_linux-x64_bin.deb
    - apt install ./jdk-21_linux-x64_bin.deb -y
  script:
    - /tmp/java-file-scorer/score.sh | tee public/lint/lint.txt
    - tail -n 1 public/lint/lint.txt > public/badges/$CI_JOB_NAME.score
  after_script:
    - anybadge --overwrite --label $CI_JOB_NAME --value=$(cat public/badges/$CI_JOB_NAME.score) --file=public/badges/$CI_JOB_NAME.svg 4=red 6=orange 8=yellow 10=green
    - |
      echo "Your score is: $(cat public/badges/$CI_JOB_NAME.score)"
  artifacts:
    paths:
      - public
    when: always
